import { FoodNutrientParsed } from './FoodNutrientParsed';

export const ESSENTIAL_NUTRIENTS_DATA: FoodNutrientParsed[] = [
  // --- MACRONUTRIENTS ---
  {
    nutrientName: 'Energy',
    aliases: ['Energy'],
    label: 'Energy',
    unitName: 'kcal',
    dailyValueMen: 2500,
    dailyValueWomen: 2000,
    value: 0,
  },
  {
    nutrientName: 'Protein',
    aliases: ['Protein', 'Protein (g)'],
    label: 'Protein',
    unitName: 'g',
    dailyValueMen: 98,
    dailyValueWomen: 77,
    value: 0,
  },
  {
    nutrientName: 'Total lipid (fat)',
    aliases: ['Total lipid (fat)', 'Total Fat'],
    label: 'Fat',
    unitName: 'g',
    dailyValueMen: 70,
    dailyValueWomen: 70,
    value: 0,
  },
  {
    nutrientName: 'Carbohydrate, by difference',
    aliases: ['Carbohydrate, by difference', 'Carbohydrate, by summation'],
    label: 'Carbs',
    unitName: 'g',
    dailyValueMen: 300,
    dailyValueWomen: 300,
    value: 0,
  },
  {
    nutrientName: 'Fiber, total dietary',
    aliases: ['Fiber, total dietary', 'Total dietary fiber'],
    label: 'Fiber',
    unitName: 'g',
    dailyValueMen: 38,
    dailyValueWomen: 25,
    value: 0,
  },
  {
    nutrientName: 'Sugars, Total',
    aliases: ['Sugars, Total', 'Total sugars', 'Sugars, total including NLEA'],
    label: 'Sugars',
    unitName: 'g',
    dailyValueMen: 36,
    dailyValueWomen: 25,
    value: 0,
  },

  // --- MINERALS ---
  {
    nutrientName: 'Calcium, Ca',
    aliases: ['Calcium, Ca', 'Calcium'],
    label: 'Calcium',
    unitName: 'mg',
    dailyValueMen: 1000,
    dailyValueWomen: 1000,
    value: 0,
  },
  {
    nutrientName: 'Iron, Fe',
    aliases: ['Iron, Fe', 'Iron'],
    label: 'Iron',
    unitName: 'mg',
    dailyValueMen: 8,
    dailyValueWomen: 18,
    value: 0,
  },
  {
    nutrientName: 'Magnesium, Mg',
    aliases: ['Magnesium, Mg', 'Magnesium'],
    label: 'Magnesium',
    unitName: 'mg',
    dailyValueMen: 400,
    dailyValueWomen: 310,
    value: 0,
  },
  {
    nutrientName: 'Potassium, K',
    aliases: ['Potassium, K', 'Potassium'],
    label: 'Potassium',
    unitName: 'mg',
    dailyValueMen: 3400,
    dailyValueWomen: 2600,
    value: 0,
  },
  {
    nutrientName: 'Sodium, Na',
    aliases: ['Sodium, Na', 'Sodium'],
    label: 'Sodium',
    unitName: 'mg',
    dailyValueMen: 2300,
    dailyValueWomen: 2300,
    value: 0,
  },
  {
    nutrientName: 'Zinc, Zn',
    aliases: ['Zinc, Zn', 'Zinc'],
    label: 'Zinc',
    unitName: 'mg',
    dailyValueMen: 11,
    dailyValueWomen: 8,
    value: 0,
  },

  // --- VITAMINS ---
  {
    nutrientName: 'Vitamin A, RAE',
    aliases: ['Vitamin A, IU'],
    label: 'Vit A',
    unitName: 'µg',
    dailyValueMen: 900,
    dailyValueWomen: 700,
    value: 0,
    legacyConversion: {
      fromUnit: 'IU',
      toUnit: 'µg',
      formula: (val: number) => val / 3.33,
    },
  },
  {
    nutrientName: 'Vitamin C, total ascorbic acid',
    aliases: ['Ascorbic acid'],
    label: 'Vit C',
    unitName: 'mg',
    dailyValueMen: 90,
    dailyValueWomen: 75,
    value: 0,
  },
  {
    nutrientName: 'Vitamin D (D2 + D3)',
    aliases: ['Vitamin D', 'Vitamin D, IU'],
    label: 'Vit D',
    unitName: 'µg',
    dailyValueMen: 15,
    dailyValueWomen: 15,
    value: 0,
    legacyConversion: {
      fromUnit: 'IU',
      toUnit: 'µg',
      formula: (val: number) => val * 0.025,
    },
  },
  {
    nutrientName: 'Vitamin E (alpha-tocopherol)',
    aliases: ['Vitamin E, IU'],
    label: 'Vit E',
    unitName: 'mg',
    dailyValueMen: 15,
    dailyValueWomen: 15,
    value: 0,
    legacyConversion: {
      fromUnit: 'IU',
      toUnit: 'mg',
      formula: (val: number) => val * 0.67,
    },
  },
  {
    nutrientName: 'Vitamin K (phylloquinone)',
    aliases: ['Vitamin K'],
    label: 'Vit K',
    unitName: 'µg',
    dailyValueMen: 120,
    dailyValueWomen: 90,
    value: 0,
  },
  {
    nutrientName: 'Vitamin B-6',
    aliases: ['Vitamin B-6', 'Pyridoxine'],
    label: 'Vit B6',
    unitName: 'mg',
    dailyValueMen: 1.7,
    dailyValueWomen: 1.5,
    value: 0,
  },
  {
    nutrientName: 'Vitamin B-12',
    aliases: ['Vitamin B-12', 'Cobalamin'],
    label: 'Vit B12',
    unitName: 'µg',
    dailyValueMen: 2.4,
    dailyValueWomen: 2.4,
    value: 0,
  },
];
