import { FoodNutrientParsed } from './FoodNutrientParsed';

export const ESSENTIAL_NUTRIENTS_DATA: FoodNutrientParsed[] = [
  { nutrientName: 'Energy', label: 'Energy', value: 0, unitName: 'kcal', dailyValueMen: 2500, dailyValueWomen: 2000 },
  { nutrientName: 'Protein', label: 'Protein', value: 0, unitName: 'g', dailyValueMen: 98, dailyValueWomen: 77 },
  { nutrientName: 'Total lipid (fat)', label: 'Fat', value: 0, unitName: 'g', dailyValueMen: 70, dailyValueWomen: 70 },
  {
    nutrientName: 'Carbohydrate, by difference',
    label: 'Carbs',
    value: 0,
    unitName: 'g',
    dailyValueMen: 300,
    dailyValueWomen: 300,
  },
  {
    nutrientName: 'Fiber, total dietary',
    label: 'Fiber',
    value: 0,
    unitName: 'g',
    dailyValueMen: 38,
    dailyValueWomen: 25,
  },
  {
    nutrientName: 'Sugars, total including NLEA',
    label: 'Sugars',
    value: 0,
    unitName: 'g',
    dailyValueMen: 36,
    dailyValueWomen: 25,
  },

  {
    nutrientName: 'Calcium, Ca',
    label: 'Calcium',
    value: 0,
    unitName: 'mg',
    dailyValueMen: 1000,
    dailyValueWomen: 1000,
  },
  { nutrientName: 'Iron, Fe', label: 'Iron', value: 0, unitName: 'mg', dailyValueMen: 8, dailyValueWomen: 18 },
  {
    nutrientName: 'Magnesium, Mg',
    label: 'Magnesium',
    value: 0,
    unitName: 'mg',
    dailyValueMen: 400,
    dailyValueWomen: 310,
  },
  {
    nutrientName: 'Potassium, K',
    label: 'Potassium',
    value: 0,
    unitName: 'mg',
    dailyValueMen: 3400,
    dailyValueWomen: 2600,
  },
  { nutrientName: 'Sodium, Na', label: 'Sodium', value: 0, unitName: 'mg', dailyValueMen: 2300, dailyValueWomen: 2300 },
  { nutrientName: 'Zinc, Zn', label: 'Zinc', value: 0, unitName: 'mg', dailyValueMen: 11, dailyValueWomen: 8 },

  {
    nutrientName: 'Vitamin A, RAE',
    label: 'Vit A',
    value: 0,
    unitName: 'µg',
    dailyValueMen: 900,
    dailyValueWomen: 700,
  },
  {
    nutrientName: 'Vitamin C, total ascorbic acid',
    label: 'Vit C',
    value: 0,
    unitName: 'mg',
    dailyValueMen: 90,
    dailyValueWomen: 75,
  },
  {
    nutrientName: 'Vitamin D (D2 + D3)',
    label: 'Vit D',
    value: 0,
    unitName: 'µg',
    dailyValueMen: 15,
    dailyValueWomen: 15,
  },
  {
    nutrientName: 'Vitamin E (alpha-tocopherol)',
    label: 'Vit E',
    value: 0,
    unitName: 'mg',
    dailyValueMen: 15,
    dailyValueWomen: 15,
  },
  {
    nutrientName: 'Vitamin K (phylloquinone)',
    label: 'Vit K',
    value: 0,
    unitName: 'µg',
    dailyValueMen: 120,
    dailyValueWomen: 90,
  },
  { nutrientName: 'Vitamin B-6', label: 'Vit B6', value: 0, unitName: 'mg', dailyValueMen: 1.7, dailyValueWomen: 1.5 },
  {
    nutrientName: 'Vitamin B-12',
    label: 'Vit B12',
    value: 0,
    unitName: 'µg',
    dailyValueMen: 2.4,
    dailyValueWomen: 2.4,
  },
];
